### ISSUE TITLE
TypeError: string indices must be integers (Network plugin)

### ISSUE THREAD

**Issue by StreetWind** [nicolargo/glances#1054]
#### Description

glances# glances -t 5  --export-influxdb
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==2.8.8', 'console_scripts', 'glances')()
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 225, in main
    start_standalone(config=config, args=args)
  File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 108, in start_standalone
    standalone.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 117, in serve_forever
    self.schedule.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 104, in __serve_forever
    self.screen.update(self.stats)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 965, in update
    self.flush(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 943, in flush
    self.display(stats, cs_status=cs_status)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 515, in display
    __stat_display = self.__get_stat_display(stats, plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/outputs/glances_curses.py", line 470, in __get_stat_display
    args=self.args, max_width=plugin_max_width)
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_plugin.py", line 701, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_network.py", line 301, in msg_curse
    for i in sorted(self.stats, key=operator.itemgetter(self.get_key())):
TypeError: string indices must be integers

#### Versions

* Glances (glances 2.8.8):
* PSutil (psutil (5.2.0)):
* Operating System (Debian 7):

#### Logs

 ERROR -- Cannot export xx.xx.65.125.docker stats to InfluxDB (400: {"error":"unable to parse 'xx.xx.65.125.docker ': invalid field format"})

**Comment by nicolargo** [comment]
The log and the error message are not the same... I think that the crash came from the "TypeError: string indices must be integers". 

@StreetWind Can you test it without the --export-influxdb tag ?

**Comment by pawel-lmcb** [comment]
Alright the issue here is that the array of dictionaries is actually an array of dictionaries + some strings. The assumption that it's an array of all dictionaries is whats causing the exception.

For example locally on my mac, I get:

[{"time_since_update": 3.1493468284606934, "cx": 0, "is_up": false, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "gif0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 268, "cumulative_tx": 268, "interface_name": "utun0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "en2"}, {"time_since_update": 3.1493468284606934, "cx": 10076, "is_up": true, "key": "interface_name", "speed": 0, "tx": 4182, "cumulative_rx": 5381833187, "rx": 5894, "cumulative_cx": 7326110614, "cumulative_tx": 1944277427, "interface_name": "en0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "en1"}, {"time_since_update": 3.1493468284606934, "cx": 26904, "is_up": true, "key": "interface_name", "speed": 0, "tx": 13452, "cumulative_rx": 2574442388, "rx": 13452, "cumulative_cx": 5148884776, "cumulative_tx": 2574442388, "interface_name": "lo0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "en3"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "en4"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 342, "cumulative_tx": 342, "interface_name": "bridge0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "p2p0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": false, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 0, "cumulative_tx": 0, "interface_name": "stf0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 0, "rx": 0, "cumulative_cx": 278822, "cumulative_tx": 278822, "interface_name": "awdl0"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 48558, "rx": 0, "cumulative_cx": 102600, "cumulative_tx": 54042, "interface_name": "utun1"}, {"time_since_update": 3.1493468284606934, "cx": 0, "is_up": true, "key": "interface_name", "speed": 0, "tx": 0, "cumulative_rx": 218750, "rx": 0, "cumulative_cx": 284738, "cumulative_tx": 65988, "interface_name": "en5"}]

While on an EC2 instance I get:

[{"time_since_update": 4.145414113998413, "cx": 200, "is_up": true, "key": "interface_name", "speed": 0, "tx": 100, "cumulative_rx": 259754668, "rx": 100, "cumulative_cx": 519509336, "cumulative_tx": 259754668, "interface_name": "lo"}, {"time_since_update": 4.145414113998413, "cx": 6253, "is_up": true, "key": "interface_name", "speed": 0, "tx": 4824, "cumulative_rx": 1076118731, "rx": 1429, "cumulative_cx": 1751374785, "cumulative_tx": 675256054, "interface_name": "eth0"}, "network_rx_critical", "network_rx_warning", "network_tx_critical", "network_rx_careful", "network_tx_warning", "history_size", "network_tx_careful"]

**Comment by pawel-lmcb** [comment]
FYI you have a similar bug in glances_percpu.py in self.get_alert(cpu[stat], header=stat)))

For some reason self.stats is also a collection of dictionaries + strings.

I'm pretty new to python, but something like iterating through that list and just appending the dictionaries to a new list and swapping that out appears to stop the crashing.

I'm sure that it's not the most efficient solution though.

**Comment by pawel-lmcb** [comment]
Talking about this guy here
https://github.com/nicolargo/glances/blob/master/glances/plugins/glances_percpu.py#L109

**Comment by nicolargo** [comment]
@pawel-lmcb Should be corrected by the latest commit. Can you please test the DEVELOP branch ?
