### ISSUE TITLE
New export plugin: standard and configurable Restfull exporter

### ISSUE THREAD

**Issue by kentonbmax** [nicolargo/glances#1129]
Provide the ability to post glances json data to restful endpoint.

**Comment by nicolargo** [comment]
Post to what kind of endpoint, which API ?

**Comment by nicolargo** [comment]
@kentonbmax is your need the same that the one describe in issue https://github.com/nicolargo/glances/issues/1109 ?

**Comment by kentonbmax** [comment]
Yes it looks to be the same.

**Comment by nicolargo** [comment]
Example:

```
 full_stats = GlancesStats(config, args)
 full_stats.update()
 #Post data to api endpoint.
 data = json.dumps(full_stats.getAllAsDict())
 requests.post('http://domain.com/server/stats', data=data, allow_redirects=True)
```

**Comment by nicolargo** [comment]
Will try to implement it for the next release (Glances 2.11).

@kentonbmax / @aftabnaveed  can you test it when the development will be ready ?

**Comment by kentonbmax** [comment]
yes

**Comment by aftabnaveed** [comment]
Yes

**Comment by nicolargo** [comment]
I have made a first implementation, nevertheless i am not sure that the way data are exported by Glances fill yours needs. For the moment, each plugins(CPU, MEM, DISK, NETWORK...) export the stats individually. So, for the new Restful exporter, you will have one POST message per plugin. I can not change the global Glances architecture only for this exporter, so i can not export all the stats in one POST message.

I have a question concerning the endpoint where the Restful post will be consume. Do you have the control off the consumer ? Is the URL could be  dynamic http://domain.com/server/stats/<pluginname> instead of static http://domain.com/server/stats ?

**Comment by nicolargo** [comment]
@kentonbmax / @aftabnaveed The feature is available in the DEVELOP branch, it implement a single JSON POST to an endpoint define in the configuration file. 

All the explanations are in the export module documentation: http://glances.readthedocs.io/en/develop/gw/restful.html

For the validation, i use this simple Python Restful server: https://github.com/nicolargo/pythonarena/blob/master/bottle/bottle_restfulserver.py

Can you test it with your owns endpoints ?

Do not hesitate to send me back your feeling concerning the implementation.

**Comment by aftabnaveed** [comment]
@nicolargo  Looks good! However, one thing seems to be missing which I use the most in my application and that is the QuickLook plugin http://glances.readthedocs.io/en/develop/aoa/quicklook.html. Unless I am missing something here?.  Anyway, this is my restful API endpoint output

https://pastebin.com/vLMLj3sD

**Comment by nicolargo** [comment]
@aftabnaveed Quickview is a "meta plugin" and did not grab any stats. It just merge stats from others plugins (cpu, mem and swap). It's why it is not exported.

**Comment by aftabnaveed** [comment]
OK cool. I would need to adjust my app I guess. When do you think it will merge with the master branch?

**Comment by nicolargo** [comment]
Before the end of august.
