### ISSUE TITLE
REST API network tx values

### ISSUE THREAD

**Issue by lediszep** [nicolargo/glances#1406]
I'm building a webpage so I can display the servers eth0 upload speeds and more. 

I use this api call to get the TX values for eth0: http://localhost:61208/api/3/network
It returns "tx" => "12718646" is this in bits or bytes? How would I output that amount to Mbps in PHP?

**Comment by nicolargo** [comment]
The http://localhost:61208/api/3/network return a list of dicts. One dict per network interface.

A example of dict:

```
{'time_since_update': 3.5635,
 'cx': 12742,
 'is_up': True,
 'key': 'interface_name',
 'speed': 0,
 'tx': 4760,
 'cumulative_rx': 9693638057,
 'rx': 7982,
 'cumulative_cx': 10162268131,
 'cumulative_tx': 468630074,
 'interface_name': 'wlp2s0'}
```

The tx is compute as following: tx = tx(current) - tx(last). The unit is in byte.
In order to display a byte rate, you should divide it by time_since_update.
Finally to display a bit rate, you should multiply by 8.
