### ISSUE TITLE
Add lighttpd reverse proxy config to the wiki

### ISSUE THREAD

**Issue by jonesaaronj** [nicolargo/glances#1643]
How about adding the reverse proxy config for lighttpd.  It took me some time to figure it out and thought others might want it too.

```
$HTTP["url"] =~ "^/glances" {
    url.rewrite-once = ( "^(/glances)$" => "$1/" )
    proxy.server = ("" => (( "host" => "localhost", "port" => 61208 )))
    proxy.header = ( "map-urlpath" => ( "/glances" => "" ) )
}
```

**Comment by nicolargo** [comment]
Thanks @jonesaaronj 

Just add it to the Wiki: https://github.com/nicolargo/glances/wiki/Reverse-proxy-to-the-Glances-Web-UI#lighttpd

Nicolas

**Comment by p1r473** [comment]
@jonesaaronj  I added this into /etc/lighttpd/conf-available/ and made a symlink to /etc/lighttpd/conf-enabled/
its sort of working because when I visit the URL I get:
![image](https://user-images.githubusercontent.com/9235633/133298295-5e50c585-2206-4593-89a9-879faa9c87c0.png)
But the page is totally blank
![image](https://user-images.githubusercontent.com/9235633/133298329-8ad80895-d6d7-4e40-821e-3a52672e1387.png)

**Comment by p1r473** [comment]
I ended up just listening on a different port. Rewriting the /glances was also messing up the javascript path
```
$SERVER["socket"] == ":81" {
    server.document-root        = "/usr/local/lib/python3.7/dist-packages/glances/outputs/static/public"
    proxy.server = ("" => (( "host" => "localhost", "port" => 61208 )))
}
```
