### ISSUE TITLE
Optimize Network and DiskIO space by not displaying 0 stats

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#1787]
**Is your feature request related to a problem? Please describe.**

For the moment, Glances display stats even if it is always set to 0.
Example: DiskIO, Network...

**Describe the solution you'd like**

Only display the stats from the moment where its value is is != 0.

**Comment by nicolargo** [comment]
Done in the Curse interface.

Before:
![before](https://user-images.githubusercontent.com/776747/105572994-bf214300-5d5a-11eb-82e5-6b503a71c994.png)

After:
![after](https://user-images.githubusercontent.com/776747/105573000-c8121480-5d5a-11eb-89da-7f65b09ab2d7.png)

@notFloran Please can you make the change on the WebUI for Network and DiskIO plugin. A new field called hidden is available in the views dictionnary.

**Comment by fcalvet** [comment]
Hi,

Using glances 3.1.6.1 (Ubuntu 20.10 64bit / Linux 5.8.0-41-generic), I've got the following issue using the Curse interface:
* in the DISK I/O section: the whole list becomes empty during a few refresh intervals (and is shown again after); it can also happen that only half the list is shown.
* in the NETWORK section: the lo interface is rarely shown (but sometimes appears during a refresh interval).

Both issues weren't notice on previously used version 3.1.5

I believe this could be related to the proposed improvement here as it seems that instead of checking if the value as never been different from zero from the start-up of glances (and as such never removing items from network/disk lists), we could be checking whether in the last interval the info to display is 0 (or something else resulting in the transient behaviour).
(if you prefer a separate issue, sorry in advance and I can open one).

As a remark, this issue is also not listed in the changelog for 3.1.6 despite commit c3ef20c being included.

**Comment by nicolargo** [comment]
My mistake... The commit c3ef20c should not have been in the develop branch... 

I will publish a patch in the 3.1.6.2 version. The optimize behavor will be desabled by default (you can enable it by adding the hide_zero=True option in the network and diskio sections of the Glances logs file).

Second step will be to correct the error... :)

**Comment by imdebating** [comment]
Thanks for the update on this -- I was wracking my brain to see what was going on :) Couldn't find anything in the released source or documentation. 

Looking forward to this but maybe we could have some "sticky" items we can always keep in the list, i.e. I would never want my main HDD or IF to disappear with 0, but maybe it doesn't matter for my virtual interfaces and can save space.

**Comment by nicolargo** [comment]
Done in Glances 4.2.0 thanks to the hide_zero option.
