### ISSUE TITLE
Export to graphite

### ISSUE THREAD

**Issue by soichih** [nicolargo/glances#1854]
Similar request to https://github.com/nicolargo/glances/issues/455 

Is it possible to export glances metrics to graphite DB?

**Comment by nicolargo** [comment]
Not for the moment...
But it should be easy to add a new exporter thanks to the https://pypi.org/project/graphyte/ lib.
I will have a look on it.

**Comment by nicolargo** [comment]
Hi @soichih 

a first implementation of the feature has been done in the  branch https://github.com/nicolargo/glances/tree/issue1854

Unfortunately, when i test it with my local Graphite Server (inside a Docker container), only some stats are exported:

![image](https://user-images.githubusercontent.com/776747/117771768-bb94c780-b236-11eb-95e5-8bc75d5ab67e.png)

Same behavor with Graphyte and GraphiteSender client. Perhaps the issue came from my server (https://github.com/nicolargo/docker-graphite-grafana)...

Any chance to test this branch on your side ?

Nicolas

**Comment by nicolargo** [comment]
Ok good news... 

The issue may come from my server.

Do you see any additional feature for this issue request ?

I will merge it to the develop branch.

**Comment by soichih** [comment]
Thanks! It did take a bit for cpu metrics to show up on grafana though.. I am not sure why. Maybe you had to wait also? Thank you for working on this.

I don't have anything specific to graphite, but is there anyway to send metrics less frequently for metrics that doesn't change too often? For example, disk usage info can be sent every 15 minutes while I want to send cpu load metrics sent every 5-10 seconds?

**Comment by nicolargo** [comment]
Merged into develop branch. Will be release in version 3.1.8.
