### ISSUE TITLE
Password is no longer accepted since version 3.4.0.

### ISSUE THREAD

**Issue by Shadow27374** [nicolargo/glances#2410]
Password is no longer accepted since version 3.4.0. Per Docker back to version 3.3.1 fixes the problem and the password is accepted again.

Which logs are needed?

**Comment by RazCrimson** [comment]
@Shadow27374 

Thanks for the issue report.

I think this problem would be corrected when #2406 gets fixed.

Please stick with the older version until that is resolved.

**Comment by Antiz96** [comment]
@Shadow27374 I think you actually have to re-generate the password once again. 
From what I can tell, since `v3.4.0`, glances uses a different stronger encryption algorithm for passwords (you can compare the content of a v3.3.X generated password file and a v3.4.X one to see it).

To make the switch to the new expected algorithm and fix this issue, you'll have to re-generate your password on glances `v3.4.X` using [this documentation](https://github.com/nicolargo/glances/blob/develop/docs/docker.rst#option-1) (at least, this is what I had to do on my side). 
However, `v3.4.X` has another issue where the `glances` binary itself isn't in the PATH and thus cannot be called directly (but this is worked in on #2406). I the mean time, you'll have to use the full absolute path of the command to regenerate your password, like so:
`/venv/bin/python3 -m glances -s --password`

**Comment by Shadow27374** [comment]
Thanks that worked but unfortunately the new version does not show me any containers.

**Comment by RazCrimson** [comment]
@Shadow27374 
Could you create a new issue on that if the problem still persists?

Closing issue as original problem is resolved.
