### ISSUE TITLE
Wrong `used` and `free` values for ZFS filesystem

### ISSUE THREAD

**Issue by VeloAddict** [nicolargo/glances#2626]
Installed ubuntu-latest and ubuntu-dev, same results.

<img width="495" alt="image" src="https://github.com/nicolargo/glances/assets/36549/e6852ced-6753-42c8-a3ae-e8ddf8261def">
<img width="727" alt="image" src="https://github.com/nicolargo/glances/assets/36549/20dcf3a3-4406-45d1-b4bd-7ad2b811107c">

<img width="444" alt="image" src="https://github.com/nicolargo/glances/assets/36549/42958c78-db41-48b3-b1ea-3c5c21c24322">
<img width="454" alt="image" src="https://github.com/nicolargo/glances/assets/36549/4ae9c7e8-63d6-4663-898e-17da32ed1a74">

**Comment by nicolargo** [comment]
Not reproduced on my side:

![image](https://github.com/nicolargo/glances/assets/776747/97bfc216-21a7-4068-9f0d-57f789b6d0ba)

**Comment by VeloAddict** [comment]
@nicolargo try to create more filesystems, write something into them, also run Glances in docker.

I created my own API for my needs :)

**Comment by crafty35a** [comment]
I'm running into this issue as well. It looks like Glances is using the REFER column as the amount of used space. @nicolargo, your example is showing basically the same value for REFER and USED, so maybe that's why you are not able to reproduce the issue?

![image](https://github.com/user-attachments/assets/4a1c8954-76fd-4ede-9722-067d8358bbce)
![image](https://github.com/user-attachments/assets/e5936b8f-cadd-4d87-b1a9-968afd1a25a1)
Glances:
![image](https://github.com/user-attachments/assets/281a66a0-3a0d-467f-92d2-1cca0da6dc12)

If it helps, this is a mirrored ZFS pool containing two 2TB drives on UnRAID:
![image](https://github.com/user-attachments/assets/d2b9f27a-d035-4c64-b0c6-65ee3cc30d01)

**Comment by zatricky** [comment]
I'm under correction here as I'm not that familiar with the Glances codebase as a whole - but I am researching this particular area for a project.

It looks to me that specific [support](https://github.com/nicolargo/glances/issues/873) for zfs is not yet available. Glances uses [psutil.disk_usage()](https://github.com/nicolargo/glances/blob/develop/glances/plugins/fs/__init__.py#L171C28-L171C60). On posix-like systems, psutil in turn [calls](https://github.com/giampaolo/psutil/blob/master/psutil/_psposix.py#L185C14-L185C30) [os.statvfs()](https://docs.python.org/3/library/os.html#os.statvfs), which is a Python builtin.

To help figure out where the problem may lie, as a regular user, what output do you get from:

    df /mnt/cache

and also:

    python <<EOF
    import os
    print(os.statvfs('/mnt/cache'))
    EOF

**Comment by crafty35a** [comment]
![image](https://github.com/user-attachments/assets/7fd28780-358e-4e02-b154-95416f570fe4)
![image](https://github.com/user-attachments/assets/f116f0cd-5528-4aad-81ce-b428f180e38a)

**Comment by zatricky** [comment]
Based on the `df` results, Glances is already returning the correct values that the *system* returns. The data returned for `os.statvfs()` is also consistent with both of them, of course.

This leads me to believe that it is a bug in how the zfs module represents the statistics to the kernel. The only fix Glances can offer is to implement specific support for zfs. See the existing issue: #873.
