### ISSUE TITLE
[Documentation] Docker compose password unrecognized arguments when applying docs.

### ISSUE THREAD

**Issue by IGLADI** [nicolargo/glances#2698]
**Describe the bug**
When applying ``- GLANCES_OPT="-w --password"`` in docker compose it doesn't recognize the argument when the docs refer to this (see below)

**To Reproduce**
Follow [this part](https://github.com/nicolargo/glances/blob/develop/docs/docker.rst#option-1) of the doc

**Expected behavior**
The container starting like it does without the arg but then with a password protected web gui

**Screenshots**
![image](https://github.com/nicolargo/glances/assets/128155180/71c7f9bb-ac27-46fb-9e32-6ddba4460810)

**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Ubuntu 22.04.4 LTS
 - Glances & psutil versions: docker image: ``nicolargo/glances:latest-full``
 - How do you install Glances (Pypi package, script, package manager, source): Docker compose
 - Glances test (only available with Glances 3.1.7 or higher): not linked?

**Comment by IGLADI** [comment]
Setting it to ``"GLANCES_OPT=-w --password"`` fixes the issue, only the docs have to be updated ig?

**Comment by nicolargo** [comment]
Documentation updated.

Thanks for the issue report @IGLADI

**Comment by kevincw01** [comment]
I'm getting this same error with the corrected documentaion e.g. ` environment:
      - GLANCES_OPT="-w --password"
`

**Comment by kevincw01** [comment]
ok after digging in further this new method is working but it looks like its failing because by default no password file exists.  So what you have to do is first start the container using with a docker-compose.yml that does not contain the --password option.  Then while it's running attach via `docker exec -it dockercontainer sh`.  Now run `glances -w --password` and set the password and make sure to choose the option to save it when asked.  Then exit the docker attach and do `docker cp dockercontainer:/root/.config/glances/glances.pwd .`  which copies the password file to your current directory. Now stop the container and edit the docker-compose.yml file to add in --password after the -w option for docker_opts.  Also in the same file add an additional volume for the password file. ` - "./glances.pwd:/root/.config/glances/glances.pwd"`  Now do `docker compose up` again and you will see that the container no longer restarts endlessly when --password is specified because it can find the password file.  I hope this helps someone else or maybe me when I try to do this again on my next attempt in a year or two.
