### ISSUE TITLE
GlancesAutoInstall claims to be incompliant with (Rpm-based) Rosa

### ISSUE THREAD

**Issue by rprosvirin** [nicolargo/glances#2740]
**Describe the bug**
When trying to install glances by running 

> curl -L https://bit.ly/glances | /bin/bash

GlancesAutoInstall script throws an error:
Detected system: rosa
Sorry, GlancesAutoInstall script is not compliant with your system.
Please read: https://github.com/nicolargo/glances#installation

I am running Rosa Linux (earlier Mandriva Linux) and uses dnf as a package manager.

**Comment by RazCrimson** [comment]
@rprosvirin 
Rosa Linux (earlier Mandriva Linux) is not one of the supported OSes of the autoinstall script. 

Please try to use the other ways to use glances mentioned at: https://github.com/nicolargo/glances#installation

Now since you use dnf, could you please take a look at the rpms maintained by fedora?
https://src.fedoraproject.org/rpms/glances

If you'd like the autoinstall script to support Rosa Linux, please raise an issue here:
https://github.com/nicolargo/glancesautoinstall

Closing the issue as no issues to be addresses. Please open a discussion if you need help in the following the other ways to install
