### ISSUE TITLE
Add authentication to the Web server

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#446]
Add a feature to protect the Web server interface by a login/password.

**Comment by nicolargo** [comment]
Postpone (wait refactoring of the Web UI with AngularJS ? See: https://github.com/nicolargo/glances/issues/473)

**Comment by notFloran** [comment]
I can look at that, but I have few questions : 
- the user/password will protect all the web server (api + web UI) ?
- we add two command-Line Options to set the user and password of the web server ?
- same thing for the config ?

**Comment by nicolargo** [comment]
Hi Floran,

* the user/password will protect all the web server (api + web UI) ? 
=> Yes 

* we add two command-Line Options to set the user and password of the web server ?
=> Best way is to use the --password (idem server side)

* same thing for the config ?
=> For the moment, user can not define the server password from the configuration file (only the client's password for the --browser mode)

**Comment by notFloran** [comment]
What do you think of this first try : https://github.com/notFloran/glances/commit/b0940c9c69b41d69c73c74e7370f6b769ab481af

I'm not a python developer so I hope I haven't done anything stupid.

**Comment by nicolargo** [comment]
Not tested but look ok for me. 
l will have a closer look this evening.

**Comment by notFloran** [comment]
I created a PR for the review #615

**Comment by nicolargo** [comment]
Merged in the develop branch.

@notFloran: 
[ ] Do you think that it is possible to include the authentification inside the WebUI interface (not a browser popup) ?
[ ] I did not test the Resful API authentication...

**Comment by desbma** [comment]
Just my 2 cents, but I think an authentication with just a sha256 against the password provides very little security.

We should either:
1. Use strong PBKDF like [Scrypt](https://en.wikipedia.org/wiki/Scrypt]) (it has great Python bindings, like [pylibscrypt](https://pypi.python.org/pypi/pylibscrypt))
2. Clearly document that this is not secure and not designed to be exposed in the open Internet (only for LAN, through a VPN or SSH tunnel, or behind a proxy that rate limits authentication requests)

I can help with 1) if you are interested.

**Comment by nicolargo** [comment]
Be my guest @desbma :)

**Comment by desbma** [comment]
Ok, I will submit a pull request when I have some time (probably this week end).

**Comment by nicolargo** [comment]
But two points should be discussed:

1) The encryption algorithm should be configurable (Scrypt or sha256, sha256 should be the default choose). Il want to keep a retro compatibility with third parties software
2) I just test the Scrypt lib and it use a lot of CPU and mode than 10 seconds ton encore a simple string...

![espace de travail 2_375](https://cloud.githubusercontent.com/assets/776747/7946219/b6df3a4c-0975-11e5-9603-e7dddb591a0e.png)

**Comment by desbma** [comment]
To answer your concerns:

1. Scrypt can use [MCF](https://pythonhosted.org/passlib/modular_crypt_format.html) which is the standard way of storing hashes (it is stored with an identifier for the algorithm used, so that it is backward and forward compatible).  Unfortunately, [glances currently stores `salt$password`](https://github.com/nicolargo/glances/blob/fd6c7a8934065108cc8f7b0ab3a2fa4ccf49e2f9/glances/core/glances_password.py#L85) which is non standard to my knowledge, so we would have to for example to use a new file name to discriminate between pre and post MCF. **What software third party are you mentioning, that you want to remain compatible with?**
2. Did you read some doc or the Wikipedia page about Scrypt? It is designed **precisely** so you can configure the CPU time and memory needed to calculate a hash. If it is too slow, just decrease  `n`, `r` or `P`.

**Comment by asergi** [comment]
My 2 cents:

there are better and stronger algorithms for sure, imo the current way is good enough for our needs.
We could add support for more but I don't want to depend on third-party libraries for that by default.

We could make the current method [MCF](https://pythonhosted.org/passlib/modular_crypt_format.html)-compliant (a standard that it isn't) just adding the prefix (the rounds is optional), but I think nobody cares since it's our own implementation.

**Comment by desbma** [comment]
> imo the current way is good enough for our needs.

I see two security issues :

1. A SHA256 is cheap to compute by today's standard (I hash data at +150MB/s with 1 core on my 4 year old computer), and currently there is zero protection against brute force. So anybody can send millions of auth attempts to a server. The consequences of an attacker getting access can be even worse if #476 is implemented.

2. If the password file is stolen it is reasonably feasible to find it's associated password. There is no Ethernet link speed limit like in [1], and with bitcoin mining hardware I suspect this can be done in a short time.

I agree that [2] is not a high priority but at least it should be made obvious to the user that this is not secure. The use of Scrypt is a robust way to solve both issues, but just disabling auth for 1s after a failed attempt would be enough to solve [1].

> We could add support for more but I don't want to depend on third-party libraries for that by default.

That is a valid concern, but in that case IMO we should mention clearly in the help, wiki, readme, etc. that by default the authentication provides weak security.

> We could make the current method MCF-compliant (a standard that it isn't) just adding the prefix (the rounds is optional), **but I think nobody cares since it's our own implementation**.

I agree that is why I don't understand @nicolargo's comment about compatibility with third party software

**Comment by nicolargo** [comment]
About the "third party software": i receive a lot of messages concerning the use of the Glances' XMLRPC and RESTFUL API  in private applications. For exemple a company use it to grab stats from remote server to a central home made monitoring system. They use the XMLRPC lib with the current authentication. My point of view is that the current SHA256 is strong enough for internal use (inside LAN or private WAN). Nervertheless, i am agree that we should propose a stronger algorithm for the internet use.
