### ISSUE TITLE
How to keep Glances running as a servce/script on Windows Server?

### ISSUE THREAD

**Issue by seanvree** [nicolargo/glances#915]
This is great man. Thanks a lot

Wondering how I can keep glances running on a windows server when no user is logged in?

I tried creating a bat file to run with -w switch, but as soon as the user logs off, glances closes.

Thoughts?

**Comment by nicolargo** [comment]
You should run Glances as a service.

Have a look on this procedure: http://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/

If you test it, can you tell us if th procedure is OK. I will add it to the documentation...

**Comment by seanvree** [comment]
Yeah, I've done this with most of my python based programs. I'm a huge MS guy, and a noob when it comes to py. 

The problem I see with Glances is you can't do this if there is no .PY or .exe .

**Comment by nicolargo** [comment]
You had to run the program through the following command line:

    > python.exe -m glances

**Comment by seanvree** [comment]
Perfect! Works!

Download:

https://nssm.cc/

Settings for NSSM:

Path: c;\python27\python.exe
startup dir: c:\python27\scripts
Augments: Glances.exe -w

**Comment by bzazzera** [comment]
Settings for NSSM that work fine with Windows 2012 R2 and no Unicode error :

Path: c;\python36\Scripts\glances.exe
startup dir: c:\python36\scripts
Augments: Glances.exe -C c;\python36\Scripts\glances.conf --export-influxdb --quiet

**Comment by bzazzera** [comment]
Sorry little mistake :
Augments: -C c;\python36\Scripts\glances.conf --export-influxdb --quiet

**Comment by mkanet** [comment]
Another alternative to NSSM is, [Always UP](https://www.coretechnologies.com/products/AlwaysUp/).  You can do all sorts of stuff with it that you can't with NSSM

**Comment by mkanet** [comment]
BTW:  The above solution to run Glances under Windows 10 does not work for me.  The glances.exe that I downloaded via PIP saves a Glances.exe that was created with Pyinstaller (python.exe and all the respective libraries is already builtin to the glances Windows executable).  It will actually cause an the below error:

`"SyntaxError: Non-UTF-8 code starting with '\x90' in file..."`

In other words, you don't need to proceed Glances.exe with python.exe.  If you choose to execute glances as a real python script using _your_ libraries, you will need to use the below command-line to start it.  I chose to go this route for performance reasons:

**glances-script.py -w --config C:\Users\MKANET\AppData\Local\Programs\Python\Python37\scripts\glances.conf --quiet**

You can still incorporate this into NSSM or AlwaysUP; however, just replace glances.exe with **glances-script.py**

**Comment by hugalafutro** [comment]
Hello, I am the great post necromancer.

Starting from scratch on Windows 11 with [nssm](https://nssm.cc):
installed latest python from https://www.python.org/getit/ selected to put it in PATH and not changing anything else
after python installed, in windows shell: `pip install glances windows-curses Bottle`

in directory where `nssm.exe` is: `nssm.exe install glances`
in the window that comes up 
(substitute [username] with your user name)
Path: `C:\Users\[username]\AppData\Local\Programs\Python\Python310\Scripts\glances.exe`
Startup Directory: `C:\Users\[username]\AppData\Local\Programs\Python\Python310\Scripts`
Augments: `-C C:\Users\[username]\AppData\Local\Programs\Python\Python310\share\doc\glances\glances.conf -w -q`
Done

Then in `services.msc` window I started the `glances` service and everything works, with glances being accessible on local network at `http://[ip address]:61208` (because of the `-w` for integration into [Dashy](https://github.com/Lissy93/dashy))

**Comment by FS1961** [comment]
I hate to resurrect this thing but trying to get this running on my Win10 pro 22H2.  I've tried nssm but keep getting this error.

<img width="409" height="207" alt="Image" src="https://github.com/user-attachments/assets/1e10d04f-3b0d-47ae-9d04-0fd632518904" />

I've tried this with a number of options but can't seem to get this to work.

In @hugalafutro's post above, I don't understand the Augments line.  I don't have a ..\doc\glances\glances.conf. Am I supposed to create this directory and conf file?

I'm running python 3.13 

Appreciate the leg up.
