### ISSUE TITLE
Issues with vendored minified javascript files (again) 

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/glances#919]
#### Description

Issue https://github.com/nicolargo/glances/issues/788 is coming back...

#### Versions

* Glances (glances -V): 2.7.1

**Comment by nicolargo** [comment]
@nclsHart Can you have a look ?

**Comment by nclsHart** [comment]
Is this issue blocking for packaging or is just a warning? 

I ask you this question because I don't see any acceptable way to solve this.

We could easily remove minify step in build workflow but you'll have the following counterparts:

1. lower perf
2. git nightmare with the built files (each edit twice in diff, thousands of added/removed lines, etc)

Furthermore we'll have the same issue again when we'll move to angular2 with source code probably written in typescript.

**Comment by epsilon77** [comment]
Hi 
yes, unfortunately,  this issue is blocking include the new version in Debian because it violates Debian Policy https://wiki.debian.org/EmbeddedCodeCopies

Thank you very much!

**Comment by nicolargo** [comment]
@notFloran Can you make a patch for the 2.7.3 relase ?

**Comment by nicolargo** [comment]
@epsilon77 I just release a "Debian" special tag for you: https://github.com/nicolargo/glances/releases/tag/v2.7.1_1

Please can you test it ?

**Comment by epsilon77** [comment]
Hi!!

Really, thank you very much!! for your help, Unfortunately I'll be offline for 15 days (holidays), when I return I'll look this :).. perhaps @sbadia  can take a look before

thanks again!
