### ISSUE TITLE
Abnormaly high cpu usage using Glances

### ISSUE THREAD

**Issue by Mirppc** [nicolargo/glances#986]
#### Description
In idle Glances uses an unsual percentage of one core/thread when running.  This might not be too horrible on a 6950K with over 20 cores or the upcomming Ryzen but on small embedded systems that are being monitored like a MIPS based router, rasberrypi and clones it can  be an issue.  The issue is not distro or OS specific.  I ran across the same issue on Debian, Opensuse, android, ubuntu and MacOSX 10.11.

#### Versions (systems i have up and running at the time of this post)

* Glances v2.7.1 with psutil v5.0.0  (Host: chip Kernel: 4.4.13-ntc-mlc armv7l (32 bit) Console: tty 0 Distro: Debian GNU/Linux 8 (jessie))

### Screenshot

http://paste.opensuse.org/33195406

*side note*

glances and python seems to have broke on my mac otherwise i would have pasted the info on that system too.

**Comment by nicolargo** [comment]
Hi @Mirppc ,

the problem is already know and we try to reduce the CPU consumption in next versions:

* https://github.com/nicolargo/glances/issues/958
* https://github.com/nicolargo/glances/issues/519
* https://github.com/nicolargo/glances/issues/922

Nevertheless, the core issue came from the PSUtil lib used in the processes list plugin. If you do not use the process list, you can disable it and reduce the CPU consumption using the --disable-process.

**Comment by nicolargo** [comment]
Already traced in others issues
